development:
  secret_key_base: ff8f78253a109f58634bf348a84fdc10bdd3a02bb1322126e8e8bb3aea2d3b5db208eb2831ee68c17593b10d99f66bec3402ceb2b4e7f5f7af8b49ef9c946777

  gitlab:
    main_username: zlx
    main_private_token: TsjxjdvUQHmq8YxPasso
    comment_username: junqiang
    comment_private_token: smmRpmCxWhjpz36yvLby

  redis_url: "http://localhost:6379"
  hook_base_url: 'http://test.com'

  active_repos:
    - 'lianxinzhu/smart-lion-backend'

test:
  secret_key_base: ff8f78253a109f58634bf348a84fdc10bdd3a02bb1322126e8e8bb3aea2d3b5db208eb2831ee68c17593b10d99f66bec3402ceb2b4e7f5f7af8b49ef9c946777

  gitlab:
    main_username: test
    main_private_token: authtoken
    comment_username: test
    comment_private_token: authtoken

  redis_url: "http://localhost:6379"
  hook_base_url: 'http://test.com'

  active_repos:
    - 'namespace/test'
