development:
  HOST: localhost:5000
  ENABLE_HTTPS: no
  GITHUB_CLIENT_ID: 5291bad2002aa396fc0c
  GITHUB_CLIENT_SECRET: cbce4dd5ad6b56ab1f8ca43746e5221539d056bf
  secret_key_base: ff8f78253a109f58634bf348a84fdc10bdd3a02bb1322126e8e8bb3aea2d3b5db208eb2831ee68c17593b10d99f66bec3402ceb2b4e7f5f7af8b49ef9c946777
  CHANGED_FILES_THRESHOLD: 300
  HOUND_GITHUB_USERNAME: houndci
  HOUND_GITHUB_TOKEN: hound_github_token
  QUEUE: high,medium,low
  REDISTOGO_URL: "http://localhost:6379"
  STRIPE_API_KEY: "sk_test_123"
  STRIPE_PUBLISHABLE_KEY: "pk_test_123"
  RESQUE_ADMIN_PASSWORD: 'smartlion'
  gitlab_private_token: TsjxjdvUQHmq8YxPasso  # user private token

test:
  HOST: test.host
  ENABLE_HTTPS: no
  GITHUB_CLIENT_ID: 5291bad2002aa396fc0c
  GITHUB_CLIENT_SECRET: cbce4dd5ad6b56ab1f8ca43746e5221539d056bf
  secret_key_base: test-key
  CHANGED_FILES_THRESHOLD: 300
  HOUND_GITHUB_USERNAME: houndci
  HOUND_GITHUB_TOKEN: houndgithubtoken
  QUEUE: high,medium,low
  REDISTOGO_URL: "http://localhost:6379"
  STRIPE_API_KEY: "sk_test_123"
  STRIPE_PUBLISHABLE_KEY: "pk_test_123"
